sudo: required
services:
  - docker

before_install:
  - docker build -t hoanghiep2004hy/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hoanghiep2004hy/docker-react npm run test -- --code-coverage